# Base Image
FROM golang:1.17-alpine AS build-env

# All these steps will be cached
RUN mkdir /app


WORKDIR /app
COPY go.mod .
COPY go.sum .

# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download
# COPY the source code as the last step
ADD . /app

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o guru ./...

# Run Binary
CMD ["/app/guru"]




# Minimal image for running single binaries - Optimisation if needed
# FROM scratch
# COPY --from=build-env /eguru-api /
# EXPOSE 8080
# ENTRYPOINT ["/eguru-api"]