name: Main Workflow Base - Test. Build and deploy to dockerhub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./API
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.5

    - name: Go test
      run: |
        go test -v ./...
      working-directory: ${{env.working-directory}}
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        working-directory: ${{env.working-directory}}
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/eguru:latest
