name: Main Workflow Base - Test. Build and deploy to dockerhub

on:
  push:
    branches: [ main ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.5

    - name: Go test
      run: |
        make test_api
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./API/dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/eguru:latest
  lint-format-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '17'
        cache: 'npm'
    - working-directory: ./client
      run: |
        npm ci
    - working-directory: ./client
      run: |
        npm run prettier:fix
        