name: Main Workflow Base - Test. Build and deploy to dockerhub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.5

    - name: Go test
      run: |
        cd API/
        go mod tidy
        go mod verify
        go test -v ./...
    
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Docker Build golang
      run: |
        docker build ./API -t 3n19ma/eguru:base
    
    - name: Docker Publish Container
      run: |
        docker push 3n19ma/eguru:latest