name: Frontend-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node: [17.0.1]
    steps:
      - name: Checkout Commit
      uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
      - name: Run prettier
      run: |
        npm run prettier:fix
      - name: Install dependencies
      run: |
        npm ci
      - name: Run buld
      run: |
        npm run build